# Dependencies stage
FROM node:22-alpine AS deps
# "Die aktuelle Version von pnpm ist 11.0.8 (Stand Mai 2026)" deshalb hab ichs auf 10.21.0 gesetzt damit mein build klappt
RUN corepack enable && corepack prepare pnpm@10.21.0 --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Builder stage
FROM node:22-alpine AS builder
ARG NEXT_PUBLIC_API_URL=http://localhost:8080
RUN corepack enable && corepack prepare pnpm@10.21.0 --activate
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV BUILD_STANDALONE=1
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
RUN pnpm build

# Production stage
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
